name: Build
on:
  push:
    branches:
      - main
      - beta
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: false
jobs:
  prebuild:
    strategy:
      matrix:
        include:
          - name: win32-x86
            os: windows-2019
            node: x86
            command: prebuildify
          - name: win32-x64
            os: windows-2019
            node: x64
            command: prebuildify
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          architecture: ${{ matrix.node }}
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run ${{ matrix.command }} -- ${{ matrix.args }}
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: prebuilds/
          if-no-files-found: error
      - if: failure()
        run: npx shx ls -lA
  release:
    needs: prebuild
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: prebuilds
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.AUTH_TOKEN}}